# This GitHub Actions workflow automates the process of checking dependencies for updates using Dependabot
name: Dependency Management and Vulnerability Scanning

on:
  # Trigger this workflow on a push to the main branch and for pull requests
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  schedule:
    - cron: "0 0 * * 0"  # Weekly schedule for automated security checks

jobs: 
  # Secret scanning with TruffleHog
  TruffleHog: 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }} # Necessary for pull request workflow trigger
    
    - name: Run TruffleHog Scan
      uses: edplato/trufflehog-actions-scan@master
      continue-on-error: false

    - name: Scan Results Status
      if: ${{ steps.trufflehog.outcome == 'failure' }}
      run: exit 1
      
  # Dependency checking with Snyk
  synk:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    
    - name: Run Snyk to Check for Vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    

