name: Dependency Management and Vulnerability Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  sast_scan:
    name: Run Bandit Scan (SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r . -f json -o bandit-report.json
        continue-on-error: false

      - name: Upload Bandit Scan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-findings
          path: bandit-report.json

      - name: Check if Bandit found vulnerabilities
        run: |
          if grep -q '"issue_severity": "HIGH"' bandit-report.json; then
            echo "High severity vulnerabilities detected!"
            exit 1
          elif grep -q '"issue_severity": "MEDIUM"' bandit-report.json; then
            echo "Medium severity vulnerabilities detected!"
            exit 1
          else
            echo "No vulnerabilities found by Bandit."
          fi

  trufflehog_scan:
    name: Run TruffleHog Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog Scan
        uses: edplato/trufflehog-actions-scan@master
        continue-on-error: true

      - name: Upload TruffleHog Findings
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trufflehog-findings
          path: ./trufflehog-findings.log

      - name: Check TruffleHog Scan Results
        if: failure()
        run: exit 1
