# This GitHub Actions workflow automates the process of checking dependencies for updates using Dependabot
name: Dependency Management and Vulnerability Scanning

on:
  # Trigger this workflow on a push to the main branch and for pull requests
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  schedule:
    - cron: "0 0 * * 0"  # Weekly schedule for automated security checks

jobs: 
  TruffleHog: 
    runs-on: ubuntu-latest 
    defaults: 
      run: 
        shell: bash 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3 
        with: 
          fetch-depth: 0
