# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ScanSecrets:
    name: Scan secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run TruffleHog scan
        uses: edplato/trufflehog-actions-scan@master
        id: trufflehog
      - name: Check for secrets
        if: ${{ steps.trufflehog.outputs.has_secrets == 'true' }}
        run: |
          echo "Secrets detected in the code!"
          exit 1
